nodeLinker: node-modules
yarnPath: .yarn/releases/yarn-3.6.3.cjs

npmScopes:
  fortawesome:
    npmAlwaysAuth: true
    npmAuthToken: 42A197BC-172B-4098-9468-B591D824BB78
    npmRegistryServer: 'https://npm.fontawesome.com/'

enableScripts: false
